# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

jobs:
- job: Windows 
  pool:
    name: onPrem
    demands: 
      - Agent.OS -equals Linux

  steps:
  - task: DownloadSecureFile@1
    name: ca_cert_pem
    displayName: 'Download ca.cert.pem'
    inputs:
      secureFile: 'myCACertificate.pem'
  - task: NodeTool@0
    inputs:
      versionSpec: '10.x'
    displayName: 'Install Node.js'

  - script: |
      npm install
      npm run build
    displayName: 'npm install and build'

- job: Linux
  pool:
    name: onPrem
    demands: 
      - Agent.OS -equals Linux 
  steps:
  - script: echo hello from second job